http:
  port: 8080
admin:
  port: 9876
  host: localhost

# Define here the exposed endpoints.
apiEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
  api:
    paths: "/ip"


# Define here the backend services.
serviceEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
  httpbin:
    url: 'https://httpbin.org'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

# Pipelines tie APIs and SERVICEs.
pipelines:
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
  - name: default
    apiEndpoints:
      - api
    policies:
     - rate-limit:
        - action:
            max: 10
            windowMs: 12000
            headers: false
            draft_polli_ratelimit_headers: true
            rateLimitBy: "${req.hostname}"
          
     - proxy:
        - action:
            serviceEndpoint: httpbin 
            changeOrigin: true 
